#!/bin/bash
# 手动部署指南

SERVER_IP="101.132.159.73"
SERVER_USER="root"
SERVER_PASS="Ylinteresting22@"
REMOTE_DIR="/opt/streetstamps/backend-node-v1"
CONTAINER_NAME="streetstamps-node-v1"

echo "=========================================="
echo "StreetStamps Backend 部署指南"
echo "=========================================="
echo ""
echo "请按以下步骤手动执行："
echo ""
echo "1️⃣ 登录服务器："
echo "   ssh root@${SERVER_IP}"
echo "   密码: ${SERVER_PASS}"
echo ""
echo "2️⃣ 备份数据库："
echo "   mkdir -p /opt/streetstamps/backups"
echo "   docker exec streetstamps-postgres pg_dump -U streetstamps streetstamps > /opt/streetstamps/backups/db_backup_\$(date +%Y%m%d_%H%M%S).sql"
echo ""
echo "3️⃣ 备份代码："
echo "   BACKUP_DIR=/opt/streetstamps/backups/code_\$(date +%Y%m%d_%H%M%S)"
echo "   mkdir -p \$BACKUP_DIR"
echo "   cp ${REMOTE_DIR}/server.js \$BACKUP_DIR/"
echo "   cp ${REMOTE_DIR}/package.json \$BACKUP_DIR/"
echo ""
echo "4️⃣ 在本地另一个终端，上传文件："
echo "   cd $(pwd)"
echo "   scp server.js root@${SERVER_IP}:${REMOTE_DIR}/server.js.new"
echo "   scp package.json root@${SERVER_IP}:${REMOTE_DIR}/package.json.new"
echo "   scp package-lock.json root@${SERVER_IP}:${REMOTE_DIR}/package-lock.json.new"
echo "   scp SECURITY-FIXES.md root@${SERVER_IP}:${REMOTE_DIR}/"
echo ""
echo "5️⃣ 在服务器上安装bcrypt并替换文件："
echo "   cd ${REMOTE_DIR}"
echo "   npm install bcrypt"
echo "   mv server.js.new server.js"
echo "   mv package.json.new package.json"
echo "   mv package-lock.json.new package-lock.json"
echo ""
echo "6️⃣ 重启容器："
echo "   docker restart ${CONTAINER_NAME}"
echo "   sleep 5"
echo "   docker logs ${CONTAINER_NAME} --tail 30"
echo ""
echo "7️⃣ 验证健康状态："
echo "   curl http://localhost:18080/v1/health"
echo ""
echo "=========================================="
echo "如需回滚，运行备份目录中的文件："
echo "   cp \$BACKUP_DIR/server.js ${REMOTE_DIR}/server.js"
echo "   docker restart ${CONTAINER_NAME}"
echo "=========================================="
