import Foundation

// Generated from china_cities.json (348 prefecture-level entries)
// + 2 country-level explicit entries for SG / TW (per strategyCountry handling).

let cnCityMappings: [CNCityEntry] = [
    CNCityEntry(zh: "北京市", en: "Beijing", province: "Beijing", aliases: ["Beijing Municipality", "Peking"]),
    CNCityEntry(zh: "天津市", en: "Tianjin", province: "Tianjin", aliases: ["Tianjin Municipality", "Tientsin"]),
    CNCityEntry(zh: "上海市", en: "Shanghai", province: "Shanghai", aliases: ["Shanghai Municipality"]),
    CNCityEntry(zh: "重庆市", en: "Chongqing", province: "Chongqing", aliases: ["Chongqing Municipality", "Chungking"]),
    CNCityEntry(zh: "石家庄市", en: "Shijiazhuang", province: "Hebei"),
    CNCityEntry(zh: "唐山市", en: "Tangshan", province: "Hebei"),
    CNCityEntry(zh: "秦皇岛市", en: "Qinhuangdao", province: "Hebei"),
    CNCityEntry(zh: "邯郸市", en: "Handan", province: "Hebei"),
    CNCityEntry(zh: "邢台市", en: "Xingtai", province: "Hebei"),
    CNCityEntry(zh: "保定市", en: "Baoding", province: "Hebei"),
    CNCityEntry(zh: "张家口市", en: "Zhangjiakou", province: "Hebei"),
    CNCityEntry(zh: "承德市", en: "Chengde", province: "Hebei"),
    CNCityEntry(zh: "沧州市", en: "Cangzhou", province: "Hebei"),
    CNCityEntry(zh: "廊坊市", en: "Langfang", province: "Hebei"),
    CNCityEntry(zh: "衡水市", en: "Hengshui", province: "Hebei"),
    CNCityEntry(zh: "太原市", en: "Taiyuan", province: "Shanxi"),
    CNCityEntry(zh: "大同市", en: "Datong", province: "Shanxi"),
    CNCityEntry(zh: "阳泉市", en: "Yangquan", province: "Shanxi"),
    CNCityEntry(zh: "长治市", en: "Changzhi", province: "Shanxi"),
    CNCityEntry(zh: "晋城市", en: "Jincheng", province: "Shanxi"),
    CNCityEntry(zh: "朔州市", en: "Shuozhou", province: "Shanxi"),
    CNCityEntry(zh: "晋中市", en: "Jinzhong", province: "Shanxi"),
    CNCityEntry(zh: "运城市", en: "Yuncheng", province: "Shanxi"),
    CNCityEntry(zh: "忻州市", en: "Xinzhou", province: "Shanxi"),
    CNCityEntry(zh: "临汾市", en: "Linfen", province: "Shanxi"),
    CNCityEntry(zh: "吕梁市", en: "Lvliang", province: "Shanxi", aliases: ["Lüliang", "Luliang"]),
    CNCityEntry(zh: "呼和浩特市", en: "Hohhot", province: "Inner Mongolia", aliases: ["Huhehaote"]),
    CNCityEntry(zh: "包头市", en: "Baotou", province: "Inner Mongolia"),
    CNCityEntry(zh: "乌海市", en: "Wuhai", province: "Inner Mongolia"),
    CNCityEntry(zh: "赤峰市", en: "Chifeng", province: "Inner Mongolia"),
    CNCityEntry(zh: "通辽市", en: "Tongliao", province: "Inner Mongolia"),
    CNCityEntry(zh: "鄂尔多斯市", en: "Ordos", province: "Inner Mongolia", aliases: ["Erdos"]),
    CNCityEntry(zh: "呼伦贝尔市", en: "Hulunbuir", province: "Inner Mongolia", aliases: ["Hulun Buir", "Hulunbeier"]),
    CNCityEntry(zh: "巴彦淖尔市", en: "Bayannur", province: "Inner Mongolia", aliases: ["Bayan Nur", "Bayannaoer"]),
    CNCityEntry(zh: "乌兰察布市", en: "Ulanqab", province: "Inner Mongolia", aliases: ["Wulanchabu"]),
    CNCityEntry(zh: "兴安盟", en: "Hinggan League", province: "Inner Mongolia", aliases: ["Xing'an League", "Xingan League"]),
    CNCityEntry(zh: "锡林郭勒盟", en: "Xilingol League", province: "Inner Mongolia", aliases: ["Xilin Gol League", "Xilinguole"]),
    CNCityEntry(zh: "阿拉善盟", en: "Alxa League", province: "Inner Mongolia", aliases: ["Alashan League", "Alxa"]),
    CNCityEntry(zh: "沈阳市", en: "Shenyang", province: "Liaoning", aliases: ["Mukden"]),
    CNCityEntry(zh: "大连市", en: "Dalian", province: "Liaoning", aliases: ["Dairen"]),
    CNCityEntry(zh: "鞍山市", en: "Anshan", province: "Liaoning"),
    CNCityEntry(zh: "抚顺市", en: "Fushun", province: "Liaoning"),
    CNCityEntry(zh: "本溪市", en: "Benxi", province: "Liaoning"),
    CNCityEntry(zh: "丹东市", en: "Dandong", province: "Liaoning"),
    CNCityEntry(zh: "锦州市", en: "Jinzhou", province: "Liaoning"),
    CNCityEntry(zh: "营口市", en: "Yingkou", province: "Liaoning"),
    CNCityEntry(zh: "阜新市", en: "Fuxin", province: "Liaoning"),
    CNCityEntry(zh: "辽阳市", en: "Liaoyang", province: "Liaoning"),
    CNCityEntry(zh: "盘锦市", en: "Panjin", province: "Liaoning"),
    CNCityEntry(zh: "铁岭市", en: "Tieling", province: "Liaoning"),
    CNCityEntry(zh: "朝阳市", en: "Chaoyang", province: "Liaoning"),
    CNCityEntry(zh: "葫芦岛市", en: "Huludao", province: "Liaoning"),
    CNCityEntry(zh: "长春市", en: "Changchun", province: "Jilin"),
    CNCityEntry(zh: "吉林市", en: "Jilin City", province: "Jilin", aliases: ["Jilin"]),
    CNCityEntry(zh: "四平市", en: "Siping", province: "Jilin"),
    CNCityEntry(zh: "辽源市", en: "Liaoyuan", province: "Jilin"),
    CNCityEntry(zh: "通化市", en: "Tonghua", province: "Jilin"),
    CNCityEntry(zh: "白山市", en: "Baishan", province: "Jilin"),
    CNCityEntry(zh: "松原市", en: "Songyuan", province: "Jilin"),
    CNCityEntry(zh: "白城市", en: "Baicheng", province: "Jilin"),
    CNCityEntry(zh: "延边朝鲜族自治州", en: "Yanbian", province: "Jilin", aliases: ["Yanbian Korean Autonomous Prefecture"]),
    CNCityEntry(zh: "哈尔滨市", en: "Harbin", province: "Heilongjiang", aliases: ["Haerbin"]),
    CNCityEntry(zh: "齐齐哈尔市", en: "Qiqihar", province: "Heilongjiang", aliases: ["Qiqihaer"]),
    CNCityEntry(zh: "鸡西市", en: "Jixi", province: "Heilongjiang"),
    CNCityEntry(zh: "鹤岗市", en: "Hegang", province: "Heilongjiang"),
    CNCityEntry(zh: "双鸭山市", en: "Shuangyashan", province: "Heilongjiang"),
    CNCityEntry(zh: "大庆市", en: "Daqing", province: "Heilongjiang"),
    CNCityEntry(zh: "伊春市", en: "Yichun", province: "Heilongjiang"),
    CNCityEntry(zh: "佳木斯市", en: "Jiamusi", province: "Heilongjiang"),
    CNCityEntry(zh: "七台河市", en: "Qitaihe", province: "Heilongjiang"),
    CNCityEntry(zh: "牡丹江市", en: "Mudanjiang", province: "Heilongjiang"),
    CNCityEntry(zh: "黑河市", en: "Heihe", province: "Heilongjiang"),
    CNCityEntry(zh: "绥化市", en: "Suihua", province: "Heilongjiang"),
    CNCityEntry(zh: "大兴安岭地区", en: "Daxing'anling", province: "Heilongjiang", aliases: ["Greater Khingan", "Daxinganling"]),
    CNCityEntry(zh: "南京市", en: "Nanjing", province: "Jiangsu", aliases: ["Nanking"]),
    CNCityEntry(zh: "无锡市", en: "Wuxi", province: "Jiangsu"),
    CNCityEntry(zh: "徐州市", en: "Xuzhou", province: "Jiangsu"),
    CNCityEntry(zh: "常州市", en: "Changzhou", province: "Jiangsu"),
    CNCityEntry(zh: "苏州市", en: "Suzhou", province: "Jiangsu", aliases: ["Soochow"]),
    CNCityEntry(zh: "南通市", en: "Nantong", province: "Jiangsu"),
    CNCityEntry(zh: "连云港市", en: "Lianyungang", province: "Jiangsu"),
    CNCityEntry(zh: "淮安市", en: "Huai'an", province: "Jiangsu", aliases: ["Huaian"]),
    CNCityEntry(zh: "盐城市", en: "Yancheng", province: "Jiangsu"),
    CNCityEntry(zh: "扬州市", en: "Yangzhou", province: "Jiangsu"),
    CNCityEntry(zh: "镇江市", en: "Zhenjiang", province: "Jiangsu"),
    CNCityEntry(zh: "泰州市", en: "Taizhou", province: "Jiangsu"),
    CNCityEntry(zh: "宿迁市", en: "Suqian", province: "Jiangsu"),
    CNCityEntry(zh: "杭州市", en: "Hangzhou", province: "Zhejiang"),
    CNCityEntry(zh: "宁波市", en: "Ningbo", province: "Zhejiang"),
    CNCityEntry(zh: "温州市", en: "Wenzhou", province: "Zhejiang"),
    CNCityEntry(zh: "嘉兴市", en: "Jiaxing", province: "Zhejiang"),
    CNCityEntry(zh: "湖州市", en: "Huzhou", province: "Zhejiang"),
    CNCityEntry(zh: "绍兴市", en: "Shaoxing", province: "Zhejiang"),
    CNCityEntry(zh: "金华市", en: "Jinhua", province: "Zhejiang"),
    CNCityEntry(zh: "衢州市", en: "Quzhou", province: "Zhejiang"),
    CNCityEntry(zh: "舟山市", en: "Zhoushan", province: "Zhejiang"),
    CNCityEntry(zh: "台州市", en: "Taizhou", province: "Zhejiang"),
    CNCityEntry(zh: "丽水市", en: "Lishui", province: "Zhejiang"),
    CNCityEntry(zh: "合肥市", en: "Hefei", province: "Anhui"),
    CNCityEntry(zh: "芜湖市", en: "Wuhu", province: "Anhui"),
    CNCityEntry(zh: "蚌埠市", en: "Bengbu", province: "Anhui"),
    CNCityEntry(zh: "淮南市", en: "Huainan", province: "Anhui"),
    CNCityEntry(zh: "马鞍山市", en: "Ma'anshan", province: "Anhui", aliases: ["Maanshan"]),
    CNCityEntry(zh: "淮北市", en: "Huaibei", province: "Anhui"),
    CNCityEntry(zh: "铜陵市", en: "Tongling", province: "Anhui"),
    CNCityEntry(zh: "安庆市", en: "Anqing", province: "Anhui"),
    CNCityEntry(zh: "黄山市", en: "Huangshan", province: "Anhui"),
    CNCityEntry(zh: "滁州市", en: "Chuzhou", province: "Anhui"),
    CNCityEntry(zh: "阜阳市", en: "Fuyang", province: "Anhui"),
    CNCityEntry(zh: "宿州市", en: "Suzhou", province: "Anhui"),
    CNCityEntry(zh: "六安市", en: "Lu'an", province: "Anhui", aliases: ["Luan"]),
    CNCityEntry(zh: "亳州市", en: "Bozhou", province: "Anhui"),
    CNCityEntry(zh: "池州市", en: "Chizhou", province: "Anhui"),
    CNCityEntry(zh: "宣城市", en: "Xuancheng", province: "Anhui"),
    CNCityEntry(zh: "福州市", en: "Fuzhou", province: "Fujian"),
    CNCityEntry(zh: "厦门市", en: "Xiamen", province: "Fujian", aliases: ["Amoy"]),
    CNCityEntry(zh: "莆田市", en: "Putian", province: "Fujian"),
    CNCityEntry(zh: "三明市", en: "Sanming", province: "Fujian"),
    CNCityEntry(zh: "泉州市", en: "Quanzhou", province: "Fujian"),
    CNCityEntry(zh: "漳州市", en: "Zhangzhou", province: "Fujian"),
    CNCityEntry(zh: "南平市", en: "Nanping", province: "Fujian"),
    CNCityEntry(zh: "龙岩市", en: "Longyan", province: "Fujian"),
    CNCityEntry(zh: "宁德市", en: "Ningde", province: "Fujian"),
    CNCityEntry(zh: "南昌市", en: "Nanchang", province: "Jiangxi"),
    CNCityEntry(zh: "景德镇市", en: "Jingdezhen", province: "Jiangxi"),
    CNCityEntry(zh: "萍乡市", en: "Pingxiang", province: "Jiangxi"),
    CNCityEntry(zh: "九江市", en: "Jiujiang", province: "Jiangxi"),
    CNCityEntry(zh: "新余市", en: "Xinyu", province: "Jiangxi"),
    CNCityEntry(zh: "鹰潭市", en: "Yingtan", province: "Jiangxi"),
    CNCityEntry(zh: "赣州市", en: "Ganzhou", province: "Jiangxi"),
    CNCityEntry(zh: "吉安市", en: "Ji'an", province: "Jiangxi", aliases: ["Jian"]),
    CNCityEntry(zh: "宜春市", en: "Yichun", province: "Jiangxi"),
    CNCityEntry(zh: "抚州市", en: "Fuzhou", province: "Jiangxi"),
    CNCityEntry(zh: "上饶市", en: "Shangrao", province: "Jiangxi"),
    CNCityEntry(zh: "济南市", en: "Jinan", province: "Shandong"),
    CNCityEntry(zh: "青岛市", en: "Qingdao", province: "Shandong", aliases: ["Tsingtao"]),
    CNCityEntry(zh: "淄博市", en: "Zibo", province: "Shandong"),
    CNCityEntry(zh: "枣庄市", en: "Zaozhuang", province: "Shandong"),
    CNCityEntry(zh: "东营市", en: "Dongying", province: "Shandong"),
    CNCityEntry(zh: "烟台市", en: "Yantai", province: "Shandong"),
    CNCityEntry(zh: "潍坊市", en: "Weifang", province: "Shandong"),
    CNCityEntry(zh: "济宁市", en: "Jining", province: "Shandong"),
    CNCityEntry(zh: "泰安市", en: "Tai'an", province: "Shandong", aliases: ["Taian"]),
    CNCityEntry(zh: "威海市", en: "Weihai", province: "Shandong"),
    CNCityEntry(zh: "日照市", en: "Rizhao", province: "Shandong"),
    CNCityEntry(zh: "临沂市", en: "Linyi", province: "Shandong"),
    CNCityEntry(zh: "德州市", en: "Dezhou", province: "Shandong"),
    CNCityEntry(zh: "聊城市", en: "Liaocheng", province: "Shandong"),
    CNCityEntry(zh: "滨州市", en: "Binzhou", province: "Shandong"),
    CNCityEntry(zh: "菏泽市", en: "Heze", province: "Shandong"),
    CNCityEntry(zh: "郑州市", en: "Zhengzhou", province: "Henan"),
    CNCityEntry(zh: "开封市", en: "Kaifeng", province: "Henan"),
    CNCityEntry(zh: "洛阳市", en: "Luoyang", province: "Henan"),
    CNCityEntry(zh: "平顶山市", en: "Pingdingshan", province: "Henan"),
    CNCityEntry(zh: "安阳市", en: "Anyang", province: "Henan"),
    CNCityEntry(zh: "鹤壁市", en: "Hebi", province: "Henan"),
    CNCityEntry(zh: "新乡市", en: "Xinxiang", province: "Henan"),
    CNCityEntry(zh: "焦作市", en: "Jiaozuo", province: "Henan"),
    CNCityEntry(zh: "濮阳市", en: "Puyang", province: "Henan"),
    CNCityEntry(zh: "许昌市", en: "Xuchang", province: "Henan"),
    CNCityEntry(zh: "漯河市", en: "Luohe", province: "Henan"),
    CNCityEntry(zh: "三门峡市", en: "Sanmenxia", province: "Henan"),
    CNCityEntry(zh: "南阳市", en: "Nanyang", province: "Henan"),
    CNCityEntry(zh: "商丘市", en: "Shangqiu", province: "Henan"),
    CNCityEntry(zh: "信阳市", en: "Xinyang", province: "Henan"),
    CNCityEntry(zh: "周口市", en: "Zhoukou", province: "Henan"),
    CNCityEntry(zh: "驻马店市", en: "Zhumadian", province: "Henan"),
    CNCityEntry(zh: "武汉市", en: "Wuhan", province: "Hubei"),
    CNCityEntry(zh: "黄石市", en: "Huangshi", province: "Hubei"),
    CNCityEntry(zh: "十堰市", en: "Shiyan", province: "Hubei"),
    CNCityEntry(zh: "宜昌市", en: "Yichang", province: "Hubei"),
    CNCityEntry(zh: "襄阳市", en: "Xiangyang", province: "Hubei", aliases: ["Xiangfan"]),
    CNCityEntry(zh: "鄂州市", en: "Ezhou", province: "Hubei"),
    CNCityEntry(zh: "荆门市", en: "Jingmen", province: "Hubei"),
    CNCityEntry(zh: "孝感市", en: "Xiaogan", province: "Hubei"),
    CNCityEntry(zh: "荆州市", en: "Jingzhou", province: "Hubei"),
    CNCityEntry(zh: "黄冈市", en: "Huanggang", province: "Hubei"),
    CNCityEntry(zh: "咸宁市", en: "Xianning", province: "Hubei"),
    CNCityEntry(zh: "随州市", en: "Suizhou", province: "Hubei"),
    CNCityEntry(zh: "恩施土家族苗族自治州", en: "Enshi", province: "Hubei", aliases: ["Enshi Tujia and Miao Autonomous Prefecture"]),
    CNCityEntry(zh: "长沙市", en: "Changsha", province: "Hunan"),
    CNCityEntry(zh: "株洲市", en: "Zhuzhou", province: "Hunan"),
    CNCityEntry(zh: "湘潭市", en: "Xiangtan", province: "Hunan"),
    CNCityEntry(zh: "衡阳市", en: "Hengyang", province: "Hunan"),
    CNCityEntry(zh: "邵阳市", en: "Shaoyang", province: "Hunan"),
    CNCityEntry(zh: "岳阳市", en: "Yueyang", province: "Hunan"),
    CNCityEntry(zh: "常德市", en: "Changde", province: "Hunan"),
    CNCityEntry(zh: "张家界市", en: "Zhangjiajie", province: "Hunan"),
    CNCityEntry(zh: "益阳市", en: "Yiyang", province: "Hunan"),
    CNCityEntry(zh: "郴州市", en: "Chenzhou", province: "Hunan"),
    CNCityEntry(zh: "永州市", en: "Yongzhou", province: "Hunan"),
    CNCityEntry(zh: "怀化市", en: "Huaihua", province: "Hunan"),
    CNCityEntry(zh: "娄底市", en: "Loudi", province: "Hunan"),
    CNCityEntry(zh: "湘西土家族苗族自治州", en: "Xiangxi", province: "Hunan", aliases: ["Xiangxi Tujia and Miao Autonomous Prefecture"]),
    CNCityEntry(zh: "广州市", en: "Guangzhou", province: "Guangdong", aliases: ["Canton"]),
    CNCityEntry(zh: "韶关市", en: "Shaoguan", province: "Guangdong"),
    CNCityEntry(zh: "深圳市", en: "Shenzhen", province: "Guangdong"),
    CNCityEntry(zh: "珠海市", en: "Zhuhai", province: "Guangdong"),
    CNCityEntry(zh: "汕头市", en: "Shantou", province: "Guangdong", aliases: ["Swatow"]),
    CNCityEntry(zh: "佛山市", en: "Foshan", province: "Guangdong"),
    CNCityEntry(zh: "江门市", en: "Jiangmen", province: "Guangdong"),
    CNCityEntry(zh: "湛江市", en: "Zhanjiang", province: "Guangdong"),
    CNCityEntry(zh: "茂名市", en: "Maoming", province: "Guangdong"),
    CNCityEntry(zh: "肇庆市", en: "Zhaoqing", province: "Guangdong"),
    CNCityEntry(zh: "惠州市", en: "Huizhou", province: "Guangdong"),
    CNCityEntry(zh: "梅州市", en: "Meizhou", province: "Guangdong"),
    CNCityEntry(zh: "汕尾市", en: "Shanwei", province: "Guangdong"),
    CNCityEntry(zh: "河源市", en: "Heyuan", province: "Guangdong"),
    CNCityEntry(zh: "阳江市", en: "Yangjiang", province: "Guangdong"),
    CNCityEntry(zh: "清远市", en: "Qingyuan", province: "Guangdong"),
    CNCityEntry(zh: "东莞市", en: "Dongguan", province: "Guangdong"),
    CNCityEntry(zh: "中山市", en: "Zhongshan", province: "Guangdong"),
    CNCityEntry(zh: "潮州市", en: "Chaozhou", province: "Guangdong", aliases: ["Teochew"]),
    CNCityEntry(zh: "揭阳市", en: "Jieyang", province: "Guangdong"),
    CNCityEntry(zh: "云浮市", en: "Yunfu", province: "Guangdong"),
    CNCityEntry(zh: "南宁市", en: "Nanning", province: "Guangxi"),
    CNCityEntry(zh: "柳州市", en: "Liuzhou", province: "Guangxi"),
    CNCityEntry(zh: "桂林市", en: "Guilin", province: "Guangxi", aliases: ["Kweilin"]),
    CNCityEntry(zh: "梧州市", en: "Wuzhou", province: "Guangxi"),
    CNCityEntry(zh: "北海市", en: "Beihai", province: "Guangxi", aliases: ["Pakhoi"]),
    CNCityEntry(zh: "防城港市", en: "Fangchenggang", province: "Guangxi"),
    CNCityEntry(zh: "钦州市", en: "Qinzhou", province: "Guangxi"),
    CNCityEntry(zh: "贵港市", en: "Guigang", province: "Guangxi"),
    CNCityEntry(zh: "玉林市", en: "Yulin", province: "Guangxi"),
    CNCityEntry(zh: "百色市", en: "Baise", province: "Guangxi", aliases: ["Bose"]),
    CNCityEntry(zh: "贺州市", en: "Hezhou", province: "Guangxi"),
    CNCityEntry(zh: "河池市", en: "Hechi", province: "Guangxi"),
    CNCityEntry(zh: "来宾市", en: "Laibin", province: "Guangxi"),
    CNCityEntry(zh: "崇左市", en: "Chongzuo", province: "Guangxi"),
    CNCityEntry(zh: "海口市", en: "Haikou", province: "Hainan"),
    CNCityEntry(zh: "三亚市", en: "Sanya", province: "Hainan"),
    CNCityEntry(zh: "三沙市", en: "Sansha", province: "Hainan"),
    CNCityEntry(zh: "儋州市", en: "Danzhou", province: "Hainan"),
    CNCityEntry(zh: "成都市", en: "Chengdu", province: "Sichuan"),
    CNCityEntry(zh: "自贡市", en: "Zigong", province: "Sichuan"),
    CNCityEntry(zh: "攀枝花市", en: "Panzhihua", province: "Sichuan"),
    CNCityEntry(zh: "泸州市", en: "Luzhou", province: "Sichuan"),
    CNCityEntry(zh: "德阳市", en: "Deyang", province: "Sichuan"),
    CNCityEntry(zh: "绵阳市", en: "Mianyang", province: "Sichuan"),
    CNCityEntry(zh: "广元市", en: "Guangyuan", province: "Sichuan"),
    CNCityEntry(zh: "遂宁市", en: "Suining", province: "Sichuan"),
    CNCityEntry(zh: "内江市", en: "Neijiang", province: "Sichuan"),
    CNCityEntry(zh: "乐山市", en: "Leshan", province: "Sichuan"),
    CNCityEntry(zh: "南充市", en: "Nanchong", province: "Sichuan"),
    CNCityEntry(zh: "眉山市", en: "Meishan", province: "Sichuan"),
    CNCityEntry(zh: "宜宾市", en: "Yibin", province: "Sichuan"),
    CNCityEntry(zh: "广安市", en: "Guang'an", province: "Sichuan", aliases: ["Guangan"]),
    CNCityEntry(zh: "达州市", en: "Dazhou", province: "Sichuan"),
    CNCityEntry(zh: "雅安市", en: "Ya'an", province: "Sichuan", aliases: ["Yaan"]),
    CNCityEntry(zh: "巴中市", en: "Bazhong", province: "Sichuan"),
    CNCityEntry(zh: "资阳市", en: "Ziyang", province: "Sichuan"),
    CNCityEntry(zh: "阿坝藏族羌族自治州", en: "Aba", province: "Sichuan", aliases: ["Ngawa", "Aba Tibetan and Qiang Autonomous Prefecture"]),
    CNCityEntry(zh: "甘孜藏族自治州", en: "Garze", province: "Sichuan", aliases: ["Ganzi", "Kardze", "Garze Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "凉山彝族自治州", en: "Liangshan", province: "Sichuan", aliases: ["Liangshan Yi Autonomous Prefecture"]),
    CNCityEntry(zh: "贵阳市", en: "Guiyang", province: "Guizhou"),
    CNCityEntry(zh: "六盘水市", en: "Liupanshui", province: "Guizhou"),
    CNCityEntry(zh: "遵义市", en: "Zunyi", province: "Guizhou"),
    CNCityEntry(zh: "安顺市", en: "Anshun", province: "Guizhou"),
    CNCityEntry(zh: "毕节市", en: "Bijie", province: "Guizhou"),
    CNCityEntry(zh: "铜仁市", en: "Tongren", province: "Guizhou"),
    CNCityEntry(zh: "黔西南布依族苗族自治州", en: "Qianxinan", province: "Guizhou", aliases: ["Qianxinan Buyei and Miao Autonomous Prefecture"]),
    CNCityEntry(zh: "黔东南苗族侗族自治州", en: "Qiandongnan", province: "Guizhou", aliases: ["Qiandongnan Miao and Dong Autonomous Prefecture"]),
    CNCityEntry(zh: "黔南布依族苗族自治州", en: "Qiannan", province: "Guizhou", aliases: ["Qiannan Buyei and Miao Autonomous Prefecture"]),
    CNCityEntry(zh: "昆明市", en: "Kunming", province: "Yunnan"),
    CNCityEntry(zh: "曲靖市", en: "Qujing", province: "Yunnan"),
    CNCityEntry(zh: "玉溪市", en: "Yuxi", province: "Yunnan"),
    CNCityEntry(zh: "保山市", en: "Baoshan", province: "Yunnan"),
    CNCityEntry(zh: "昭通市", en: "Zhaotong", province: "Yunnan"),
    CNCityEntry(zh: "丽江市", en: "Lijiang", province: "Yunnan"),
    CNCityEntry(zh: "普洱市", en: "Pu'er", province: "Yunnan", aliases: ["Puer", "Simao"]),
    CNCityEntry(zh: "临沧市", en: "Lincang", province: "Yunnan"),
    CNCityEntry(zh: "楚雄彝族自治州", en: "Chuxiong", province: "Yunnan", aliases: ["Chuxiong Yi Autonomous Prefecture"]),
    CNCityEntry(zh: "红河哈尼族彝族自治州", en: "Honghe", province: "Yunnan", aliases: ["Honghe Hani and Yi Autonomous Prefecture"]),
    CNCityEntry(zh: "文山壮族苗族自治州", en: "Wenshan", province: "Yunnan", aliases: ["Wenshan Zhuang and Miao Autonomous Prefecture"]),
    CNCityEntry(zh: "西双版纳傣族自治州", en: "Xishuangbanna", province: "Yunnan", aliases: ["Xishuangbanna Dai Autonomous Prefecture"]),
    CNCityEntry(zh: "大理白族自治州", en: "Dali", province: "Yunnan", aliases: ["Dali Bai Autonomous Prefecture"]),
    CNCityEntry(zh: "德宏傣族景颇族自治州", en: "Dehong", province: "Yunnan", aliases: ["Dehong Dai and Jingpo Autonomous Prefecture"]),
    CNCityEntry(zh: "怒江傈僳族自治州", en: "Nujiang", province: "Yunnan", aliases: ["Nujiang Lisu Autonomous Prefecture"]),
    CNCityEntry(zh: "迪庆藏族自治州", en: "Diqing", province: "Yunnan", aliases: ["Deqen", "Diqing Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "拉萨市", en: "Lhasa", province: "Tibet", aliases: ["Lasa"]),
    CNCityEntry(zh: "日喀则市", en: "Shigatse", province: "Tibet", aliases: ["Xigaze", "Rikaze"]),
    CNCityEntry(zh: "昌都市", en: "Qamdo", province: "Tibet", aliases: ["Changdu", "Chamdo"]),
    CNCityEntry(zh: "林芝市", en: "Nyingchi", province: "Tibet", aliases: ["Linzhi"]),
    CNCityEntry(zh: "山南市", en: "Shannan", province: "Tibet", aliases: ["Lhoka"]),
    CNCityEntry(zh: "那曲市", en: "Nagqu", province: "Tibet", aliases: ["Naqu"]),
    CNCityEntry(zh: "阿里地区", en: "Ngari", province: "Tibet", aliases: ["Ali"]),
    CNCityEntry(zh: "西安市", en: "Xi'an", province: "Shaanxi", aliases: ["Xian", "Sian"]),
    CNCityEntry(zh: "铜川市", en: "Tongchuan", province: "Shaanxi"),
    CNCityEntry(zh: "宝鸡市", en: "Baoji", province: "Shaanxi"),
    CNCityEntry(zh: "咸阳市", en: "Xianyang", province: "Shaanxi"),
    CNCityEntry(zh: "渭南市", en: "Weinan", province: "Shaanxi"),
    CNCityEntry(zh: "延安市", en: "Yan'an", province: "Shaanxi", aliases: ["Yanan"]),
    CNCityEntry(zh: "汉中市", en: "Hanzhong", province: "Shaanxi"),
    CNCityEntry(zh: "榆林市", en: "Yulin", province: "Shaanxi"),
    CNCityEntry(zh: "安康市", en: "Ankang", province: "Shaanxi"),
    CNCityEntry(zh: "商洛市", en: "Shangluo", province: "Shaanxi"),
    CNCityEntry(zh: "兰州市", en: "Lanzhou", province: "Gansu"),
    CNCityEntry(zh: "嘉峪关市", en: "Jiayuguan", province: "Gansu"),
    CNCityEntry(zh: "金昌市", en: "Jinchang", province: "Gansu"),
    CNCityEntry(zh: "白银市", en: "Baiyin", province: "Gansu"),
    CNCityEntry(zh: "天水市", en: "Tianshui", province: "Gansu"),
    CNCityEntry(zh: "武威市", en: "Wuwei", province: "Gansu"),
    CNCityEntry(zh: "张掖市", en: "Zhangye", province: "Gansu"),
    CNCityEntry(zh: "平凉市", en: "Pingliang", province: "Gansu"),
    CNCityEntry(zh: "酒泉市", en: "Jiuquan", province: "Gansu"),
    CNCityEntry(zh: "庆阳市", en: "Qingyang", province: "Gansu"),
    CNCityEntry(zh: "定西市", en: "Dingxi", province: "Gansu"),
    CNCityEntry(zh: "陇南市", en: "Longnan", province: "Gansu"),
    CNCityEntry(zh: "临夏回族自治州", en: "Linxia", province: "Gansu", aliases: ["Linxia Hui Autonomous Prefecture"]),
    CNCityEntry(zh: "甘南藏族自治州", en: "Gannan", province: "Gansu", aliases: ["Gannan Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "西宁市", en: "Xining", province: "Qinghai"),
    CNCityEntry(zh: "海东市", en: "Haidong", province: "Qinghai"),
    CNCityEntry(zh: "海北藏族自治州", en: "Haibei", province: "Qinghai", aliases: ["Haibei Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "黄南藏族自治州", en: "Huangnan", province: "Qinghai", aliases: ["Huangnan Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "海南藏族自治州", en: "Hainan", province: "Qinghai", aliases: ["Hainan Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "果洛藏族自治州", en: "Golog", province: "Qinghai", aliases: ["Guoluo", "Golog Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "玉树藏族自治州", en: "Yushu", province: "Qinghai", aliases: ["Yushu Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "海西蒙古族藏族自治州", en: "Haixi", province: "Qinghai", aliases: ["Haixi Mongol and Tibetan Autonomous Prefecture"]),
    CNCityEntry(zh: "银川市", en: "Yinchuan", province: "Ningxia"),
    CNCityEntry(zh: "石嘴山市", en: "Shizuishan", province: "Ningxia"),
    CNCityEntry(zh: "吴忠市", en: "Wuzhong", province: "Ningxia"),
    CNCityEntry(zh: "固原市", en: "Guyuan", province: "Ningxia"),
    CNCityEntry(zh: "中卫市", en: "Zhongwei", province: "Ningxia"),
    CNCityEntry(zh: "乌鲁木齐市", en: "Urumqi", province: "Xinjiang", aliases: ["Wulumuqi", "Urumchi"]),
    CNCityEntry(zh: "克拉玛依市", en: "Karamay", province: "Xinjiang", aliases: ["Kelamayi"]),
    CNCityEntry(zh: "吐鲁番市", en: "Turpan", province: "Xinjiang", aliases: ["Tulufan", "Turfan"]),
    CNCityEntry(zh: "哈密市", en: "Hami", province: "Xinjiang", aliases: ["Kumul"]),
    CNCityEntry(zh: "昌吉回族自治州", en: "Changji", province: "Xinjiang", aliases: ["Changji Hui Autonomous Prefecture"]),
    CNCityEntry(zh: "博尔塔拉蒙古自治州", en: "Bortala", province: "Xinjiang", aliases: ["Bo'ertala", "Boertala"]),
    CNCityEntry(zh: "巴音郭楞蒙古自治州", en: "Bayingol", province: "Xinjiang", aliases: ["Bayinguoleng", "Bayingolin"]),
    CNCityEntry(zh: "阿克苏地区", en: "Aksu", province: "Xinjiang", aliases: ["Akesu"]),
    CNCityEntry(zh: "克孜勒苏柯尔克孜自治州", en: "Kizilsu", province: "Xinjiang", aliases: ["Kezilesu", "Kyzylsu"]),
    CNCityEntry(zh: "喀什地区", en: "Kashgar", province: "Xinjiang", aliases: ["Kashi", "Kashghar"]),
    CNCityEntry(zh: "和田地区", en: "Hotan", province: "Xinjiang", aliases: ["Hetian", "Khotan"]),
    CNCityEntry(zh: "伊犁哈萨克自治州", en: "Ili", province: "Xinjiang", aliases: ["Yili", "Ili Kazakh Autonomous Prefecture"]),
    CNCityEntry(zh: "塔城地区", en: "Tacheng", province: "Xinjiang", aliases: ["Tarbagatay", "Qoqek"]),
    CNCityEntry(zh: "阿勒泰地区", en: "Altay", province: "Xinjiang", aliases: ["Aletai"]),
    CNCityEntry(zh: "香港特别行政区", en: "Hong Kong", province: "", iso2: "HK", aliases: ["HK", "Xianggang", "Hong Kong SAR"]),
    CNCityEntry(zh: "澳门特别行政区", en: "Macau", province: "", iso2: "MO", aliases: ["Macao", "Aomen", "Macau SAR"]),
    CNCityEntry(zh: "台北市", en: "Taipei", province: "Taiwan", iso2: "TW", aliases: ["Taibei"]),
    CNCityEntry(zh: "新北市", en: "New Taipei", province: "Taiwan", iso2: "TW", aliases: ["Xinbei"]),
    CNCityEntry(zh: "桃园市", en: "Taoyuan", province: "Taiwan", iso2: "TW"),
    CNCityEntry(zh: "台中市", en: "Taichung", province: "Taiwan", iso2: "TW", aliases: ["Taizhong"]),
    CNCityEntry(zh: "台南市", en: "Tainan", province: "Taiwan", iso2: "TW"),
    CNCityEntry(zh: "高雄市", en: "Kaohsiung", province: "Taiwan", iso2: "TW", aliases: ["Gaoxiong"]),
    CNCityEntry(zh: "基隆市", en: "Keelung", province: "Taiwan", iso2: "TW", aliases: ["Jilong"]),
    CNCityEntry(zh: "新竹市", en: "Hsinchu", province: "Taiwan", iso2: "TW", aliases: ["Xinzhu"]),
    CNCityEntry(zh: "嘉义市", en: "Chiayi", province: "Taiwan", iso2: "TW", aliases: ["Jiayi"]),
    CNCityEntry(zh: "台湾", en: "Taiwan", province: "", iso2: "TW"),
    CNCityEntry(zh: "新加坡", en: "Singapore", province: "", iso2: "SG"),
]
